In [1]:
from numpy.random import seed
seed(1)

In [2]:
import numpy as np
import pandas as pd

In [3]:
import tensorflow
tensorflow.keras.__version__

'2.4.0'

In [4]:
grammySongs = pd.read_csv('BillboardFromLast20_New/merged_songGrammy.csv')
grammySongs

Unnamed: 0_x    X                         GrammyAward  GrammyYear  \
0              14   13                       Best Rap Song        2018   
1              21   20     Best American Roots Performance        2018   
2              22   21            Best American Roots Song        2018   
3              33   32    Best Traditional R&B Performance        2017   
4              39   38  Best Country Duo/Group Performance        2017   
..            ...  ...                                 ...         ...   
139           415  414                Best Dance Recording        1999   
140           416  415  Best Female Rock Vocal Performance        1999   
141           417  416    Best Male Rock Vocal Performance        1999   
142           417  416    Best Male Rock Vocal Performance        1999   
143           421  420                      Best Rock Song        1999   

                    Genre               Name_x                 Artist  \
0                     Rap           God's Plan                  Drake   
1    American Roots Music             The Joke         Brandi Carlile   
2    American Roots Music             The Joke         Brandi Carlile   
3                     R&B              Redbone       Childish Gambino   
4                 Country           Better Man        Little Big Town   
..                    ...                  ...                    ...   
139                   Pop              Believe                   Cher   
140                  Rock  Sweet Child O' Mine            Sheryl Crow   
141                  Rock       American Woman          Lenny Kravitz   
142                  Rock       American Woman          Lenny Kravitz   
143                  Rock          Scar Tissue  Red Hot Chili Peppers   

                               Unique  Unnamed: 0_y  Acousticness  ...  \
0                     God's PlanDrake           112        0.0332  ...   
1              The JokeBrandi Carlile            26        0.3270  ...   
2              The JokeBrandi Carlile            26        0.3270  ...   
3             RedboneChildish Gambino            40        0.1830  ...   
4           Better ManLittle Big Town            46        0.1120  ...   
..                                ...           ...           ...  ...   
139                       BelieveCher            72        0.0082  ...   
140    Sweet Child O' MineSheryl Crow           199        0.0867  ...   
141       American WomanLenny Kravitz            48        0.0304  ...   
142       American WomanLenny Kravitz           156        0.0212  ...   
143  Scar TissueRed Hot Chili Peppers            39        0.0779  ...   

    Liveness Loudness  Mode               Name_y  Popularity  \
0     0.5520   -9.211     1           God's Plan          86   
1     0.2060   -5.477     1             The Joke          62   
2     0.2060   -5.477     1             The Joke          62   
3     0.1520  -10.974     1              Redbone          61   
4     0.0878   -3.663     1           Better Man          65   
..       ...      ...   ...                  ...         ...   
139   0.0509   -6.720     1              Believe          77   
140   0.1030   -3.183     1  Sweet Child O' Mine          61   
141   0.0782   -7.872     1       American Woman          64   
142   0.0730   -7.989     1       American Woman          15   
143   0.1080   -4.803     1          Scar Tissue          77   

     Popularity Calculated  Speechiness    Tempo  TimeSignature  Valence  
0                  Popular       0.1090   77.169              4    0.357  
1           Mildly Popular       0.0404   75.367              4    0.227  
2           Mildly Popular       0.0404   75.367              4    0.227  
3           Mildly Popular       0.1100  160.090              4    0.577  
4           Mildly Popular       0.0381  143.888              4    0.501  
..                     ...          ...      ...            ...      ...  
139                Popular       0.0548  132.975        

In [5]:
grammySongs1=grammySongs.drop(columns=["Unnamed: 0_x","X","GrammyAward", "GrammyYear", "Name_x","Unique","Unnamed: 0_y","Album","Artist_y","Mode","Name_y"])
grammySongs1

Genre                 Artist  Acousticness  Danceability  \
0                     Rap                  Drake        0.0332         0.754   
1    American Roots Music         Brandi Carlile        0.3270         0.236   
2    American Roots Music         Brandi Carlile        0.3270         0.236   
3                     R&B       Childish Gambino        0.1830         0.739   
4                 Country        Little Big Town        0.1120         0.514   
..                    ...                    ...           ...           ...   
139                   Pop                   Cher        0.0082         0.652   
140                  Rock            Sheryl Crow        0.0867         0.592   
141                  Rock          Lenny Kravitz        0.0304         0.688   
142                  Rock          Lenny Kravitz        0.0212         0.668   
143                  Rock  Red Hot Chili Peppers        0.0779         0.595   

     Duration  Energy  Explicit  Instrumentalness  Liveness  Loudness  \
0      198973   0.449      True          0.000083    0.5520    -9.211   
1      279373   0.578     False          0.000150    0.2060    -5.477   
2      279373   0.578     False          0.000150    0.2060    -5.477   
3      326933   0.346      True          0.002980    0.1520   -10.974   
4      263120   0.836     False          0.000000    0.0878    -3.663   
..        ...     ...       ...               ...       ...       ...   
139    239027   0.917     False          0.000000    0.0509    -6.720   
140    234133   0.865     False          0.000004    0.1030    -3.183   
141    264560   0.670     False          0.000000    0.0782    -7.872   
142    261707   0.709     False          0.000000    0.0730    -7.989   
143    215907   0.717     False          0.002740    0.1080    -4.803   

     Popularity Popularity Calculated  Speechiness    Tempo  TimeSignature  \
0            86               Popular       0.1090   77.169              4   
1            62        Mildly Popular       0.0404   75.367              4   
2            62        Mildly Popular       0.0404   75.367              4   
3            61        Mildly Popular       0.1100  160.090              4   
4            65        Mildly Popular       0.0381  143.888              4   
..          ...                   ...          ...      ...            ...   
139          77               Popular       0.0548  132.975              4   
140          61        Mildly Popular       0.0282  124.278              4   
141          64        Mildly Popular       0.0971   83.988              4   
142          15             Unpopular       0.0634   83.977              4   
143          77               Popular       0.0295   88.969              4   

     Valence  
0      0.357  
1      0.227  
2      0.227  
3      0.577  
4      0.501  
..       ...  
139    0.459  
140    0.659  
141    0.537  
142    0.610  
143    0.547  

[144 rows x 16 columns]

In [6]:
grammySongs_binary_encoded = pd.get_dummies(grammySongs1, columns=["Artist", "TimeSignature","Explicit", "Genre"])
grammySongs_binary_encoded.head()

Acousticness  Danceability  Duration  Energy  Instrumentalness  Liveness  \
0        0.0332         0.754    198973   0.449          0.000083    0.5520   
1        0.3270         0.236    279373   0.578          0.000150    0.2060   
2        0.3270         0.236    279373   0.578          0.000150    0.2060   
3        0.1830         0.739    326933   0.346          0.002980    0.1520   
4        0.1120         0.514    263120   0.836          0.000000    0.0878   

   Loudness  Popularity Popularity Calculated  Speechiness  ...  \
0    -9.211          86               Popular       0.1090  ...   
1    -5.477          62        Mildly Popular       0.0404  ...   
2    -5.477          62        Mildly Popular       0.0404  ...   
3   -10.974          61        Mildly Popular       0.1100  ...   
4    -3.663          65        Mildly Popular       0.0381  ...   

   Explicit_True  Genre_American Roots Music  Genre_Country  \
0              1                           0              0   
1              0                           1              0   
2              0                           1              0   
3              1                           0              0   
4              0                           0              1   

   Genre_Dance/Electronic Music  Genre_General  \
0                             0              0   
1                             0              0   
2                             0              0   
3                             0              0   
4                             0              0   

   Genre_Gospel/Contemporary Christian Music  Genre_Pop  Genre_R&B  Genre_Rap  \
0                                          0          0          0          1   
1                                          0          0          0          0   
2                                          0          0          0          0   
3                                          0          0          1          0   
4                                          0          0          0          0   

   Genre_Rock  
0           0  
1           0  
2           0  
3           0  
4           0  

[5 rows x 81 columns]

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [8]:
grammySongs_binary_encoded.columns

Index(['Acousticness', 'Danceability', 'Duration', 'Energy',
       'Instrumentalness', 'Liveness', 'Loudness', 'Popularity',
       'Popularity Calculated', 'Speechiness', 'Tempo', 'Valence',
       'Artist_Adele', 'Artist_Alison Krauss', 'Artist_Amy Winehouse',
       'Artist_Brad Paisley', 'Artist_Brandi Carlile', 'Artist_Britney Spears',
       'Artist_Carrie Underwood', 'Artist_Cher', 'Artist_Childish Gambino',
       'Artist_Christina Aguilera', 'Artist_Creed', 'Artist_Darius Rucker',
       'Artist_David Bowie', 'Artist_Dixie Chicks', 'Artist_Drake',
       'Artist_Eminem', 'Artist_Fantasia', 'Artist_Foo Fighters',
       'Artist_Gretchen Wilson', 'Artist_John Legend', 'Artist_John Mayer',
       'Artist_Justin Timberlake', 'Artist_Keith Urban',
       'Artist_Kendrick Lamar', 'Artist_Korn', 'Artist_Kylie Minogue',
       'Artist_Lady Gaga', 'Artist_Lenny Kravitz', 'Artist_Linkin Park',
       'Artist_Little Big Town', 'Artist_Los Lonely Boys',
       'Artist_Mariah Carey', 'Art

In [9]:
X = grammySongs_binary_encoded.drop(["Popularity","Popularity Calculated", "Artist_Adele", "TimeSignature_3","Explicit_False","Genre_American Roots Music"], axis=1)
y = grammySongs_binary_encoded["Popularity Calculated"]
print(X.shape, y.shape)

(144, 75) (144,)


In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)
X_train.head()

Acousticness  Danceability  Duration  Energy  Instrumentalness  Liveness  \
104         0.946         0.528    200280   0.308            0.0729    0.1070   
93          0.665         0.359    226493   0.518            0.0000    0.1060   
18          0.263         0.309    311893   0.492            0.0000    0.4060   
4           0.112         0.514    263120   0.836            0.0000    0.0878   
131         0.154         0.468    259933   0.640            0.0000    0.1540   

     Loudness  Speechiness    Tempo  Valence  ...  TimeSignature_5  \
104   -13.838       0.0309  156.991    0.678  ...                0   
93     -3.537       0.0302   76.572    0.135  ...                0   
18     -5.660       0.0353   77.596    0.208  ...                0   
4      -3.663       0.0381  143.888    0.501  ...                0   
131    -5.862       0.0275   79.297    0.499  ...                0   

     Explicit_True  Genre_Country  Genre_Dance/Electronic Music  \
104              0              0                             0   
93               0              1                             0   
18               0              0                             0   
4                0              1                             0   
131              0              0                             0   

     Genre_General  Genre_Gospel/Contemporary Christian Music  Genre_Pop  \
104              0                                          0          1   
93               0                                          0          0   
18               0                                          1          0   
4                0                                          0          0   
131              0                                          0          0   

     Genre_R&B  Genre_Rap  Genre_Rock  
104          0          0           0  
93           0          0           0  
18           0          0           0  
4            0          0           0  
131          0          0           1  

[5 rows x 75 columns]

In [11]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [13]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=75))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=4, activation='softmax'))

In [16]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               7600      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 404       
Total params: 18,104
Trainable params: 18,104
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
4/4 - 0s - loss: 1.4197 - accuracy: 0.2222
Epoch 2/100
4/4 - 0s - loss: 1.3464 - accuracy: 0.3333
Epoch 3/100
4/4 - 0s - loss: 1.2788 - accuracy: 0.4722
Epoch 4/100
4/4 - 0s - loss: 1.2362 - accuracy: 0.4352
Epoch 5/100
4/4 - 0s - loss: 1.1988 - accuracy: 0.4167
Epoch 6/100
4/4 - 0s - loss: 1.1655 - accuracy: 0.4167
Epoch 7/100
4/4 - 0s - loss: 1.1342 - accuracy: 0.4074
Epoch 8/100
4/4 - 0s - loss: 1.1061 - accuracy: 0.4722
Epoch 9/100
4/4 - 0s - loss: 1.0759 - accuracy: 0.5000
Epoch 10/100
4/4 - 0s - loss: 1.0428 - accuracy: 0.5833
Epoch 11/100
4/4 - 0s - loss: 1.0076 - accuracy: 0.6389
Epoch 12/100
4/4 - 0s - loss: 0.9760 - accuracy: 0.6574
Epoch 13/100
4/4 - 0s - loss: 0.9427 - accuracy: 0.6944
Epoch 14/100
4/4 - 0s - loss: 0.9083 - accuracy: 0.6852
Epoch 15/100
4/4 - 0s - loss: 0.8730 - accuracy: 0.6944
Epoch 16/100
4/4 - 0s - loss: 0.8369 - accuracy: 0.7037
Epoch 17/100
4/4 - 0s - loss: 0.8012 - accuracy: 0.7037
Epoch 18/100
4/4 - 0s - loss: 0.7659 - accuracy: 0.7130
E

In [19]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

2/2 - 0s - loss: 2.0609 - accuracy: 0.5556
Normal Neural Network - Loss: 2.060877799987793, Accuracy: 0.5555555820465088


In [20]:
encoded_predictions = model.predict_classes(X_test_scaled)
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [21]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test)}")

Predicted classes: ['Unpopular' 'Unpopular' 'Mildly Unpopular' 'Mildly Unpopular' 'Unpopular'
 'Mildly Popular' 'Mildly Unpopular' 'Mildly Popular' 'Mildly Popular'
 'Unpopular' 'Mildly Popular' 'Unpopular' 'Unpopular' 'Mildly Popular'
 'Mildly Unpopular' 'Mildly Popular' 'Mildly Popular' 'Unpopular'
 'Mildly Popular' 'Mildly Popular' 'Mildly Unpopular' 'Mildly Popular'
 'Mildly Unpopular' 'Mildly Unpopular' 'Mildly Unpopular' 'Mildly Popular'
 'Mildly Popular' 'Mildly Unpopular' 'Mildly Popular' 'Mildly Popular'
 'Unpopular' 'Mildly Unpopular' 'Mildly Unpopular' 'Mildly Unpopular'
 'Mildly Popular' 'Unpopular']
Actual Labels: ['Unpopular', 'Unpopular', 'Mildly Unpopular', 'Unpopular', 'Mildly Unpopular', 'Mildly Popular', 'Mildly Unpopular', 'Mildly Unpopular', 'Popular', 'Unpopular', 'Unpopular', 'Unpopular', 'Unpopular', 'Mildly Popular', 'Mildly Popular', 'Mildly Popular', 'Mildly Unpopular', 'Mildly Popular', 'Mildly Popular', 'Mildly Popular', 'Mildly Unpopular', 'Unpopular', 'Mi

In [22]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 

In [23]:
results = confusion_matrix(y_test, prediction_labels) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(y_test, prediction_labels))
print ('Report : ')
print (classification_report(y_test, prediction_labels) )

Confusion Matrix :
[[8 3 0 1]
 [3 5 0 1]
 [1 0 0 0]
 [3 4 0 7]]
Accuracy Score : 0.5555555555555556
Report : 
                  precision    recall  f1-score   support

  Mildly Popular       0.53      0.67      0.59        12
Mildly Unpopular       0.42      0.56      0.48         9
         Popular       0.00      0.00      0.00         1
       Unpopular       0.78      0.50      0.61        14

        accuracy                           0.56        36
       macro avg       0.43      0.43      0.42        36
    weighted avg       0.58      0.56      0.55        36



/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
