In [7]:
from numpy.random import seed
seed(1)
import numpy as np
import pandas as pd
import tensorflow
tensorflow.keras.__version__

'2.4.0'

In [8]:
songCopy = pd.read_csv('BillboardFromLast20/songAttributes_1999-2019 copy.csv')
songCopy


Unnamed: 0  Acousticness                             Album  \
0                0      0.000728  Collective Soul (Deluxe Version)   
1                1      0.018200  Collective Soul (Deluxe Version)   
2                2      0.000473  Collective Soul (Deluxe Version)   
3                3      0.000970  Collective Soul (Deluxe Version)   
4                4      0.000036  Collective Soul (Deluxe Version)   
...            ...           ...                               ...   
154926         114      0.333000       No.6 Collaborations Project   
154927         115      0.314000       No.6 Collaborations Project   
154928         116      0.467000       No.6 Collaborations Project   
154929         117      0.110000       No.6 Collaborations Project   
154930         118      0.000245       No.6 Collaborations Project   

                 Artist  Danceability  Duration  Energy  Explicit  \
0       Collective Soul         0.520    234947   0.904     False   
1       Collective Soul         0.581    239573   0.709     False   
2       Collective Soul         0.572    198400   0.918     False   
3       Collective Soul         0.596    231453   0.661     False   
4       Collective Soul         0.520    222520   0.808     False   
...                 ...           ...       ...     ...       ...   
154926       Ed Sheeran         0.747    200733   0.649     False   
154927       Ed Sheeran         0.469    204507   0.631     False   
154928       Ed Sheeran         0.778    212307   0.590     False   
154929       Ed Sheeran         0.726    190293   0.731     False   
154930       Ed Sheeran         0.631    209120   0.796     False   

        Instrumentalness  Liveness  Loudness  Mode  \
0               0.010300    0.0634    -5.030     1   
1               0.000664    0.1740    -4.909     1   
2               0.000431    0.0977    -3.324     0   
3               0.000033    0.1130    -5.051     1   
4               0.000010    0.0800    -4.553     0   
...                  ...       ...       ...   ...   
154926          0.000000    0.1720    -6.218     0   
154927          0.000000    0.1400    -6.569     0   
154928          0.000000    0.0902    -5.548     1   
154929          0.000003    0.0928    -6.304     0   
154930          0.011500    0.3800    -5.350     1   

                                                     Name  Popularity  \
0                                       Welcome All Again          35   
1                                                   Fuzzy          31   
2                                                     Dig          30   
3                                                     You          35   
4                                                 My Days          21   
...                                                   ...         ...   
154926         Nothing On You (feat. Paulo Londra & Dave)          80   
154927              I Dont Want Your Money (feat. H.E.R.)          74   
154928  1000 Nights (feat. Meek Mill & A Boogie Wit da...          75   
154929             Way To Break My Heart (feat. Skrillex)          73   
154930           BLOW (with Chris Stapleton & Bruno Mars)          72   

       Popularity Calculated  Speechiness    Tempo  TimeSignature  Valence  
0           Mildly Unpopular       0.0309  106.022              4    0.365  
1           Mildly Unpopular       0.0282  120.027              4    0.408  
2           Mildly Unpopular       0.0559  144.061              4    0.370  
3           Mildly Unpopular       0.0254  111.975              4    0.183  
4                 Unpopular        0.0318   92.721              4    0.666  
...                      ...          ...      ...            ...      ...  
154926               Popular       0.2190   88.011              4    0.840  
154927        Mildly Popular       0.0853   91.418              4    0.763  
154928               Popular       0.2700   97.995              4    0.515  
154929        Mildly Popular       0.1590 

In [19]:
songCopy1=songCopy.drop(columns=["Album","Name","Mode"])

In [30]:
X = songCopy1.drop(["Popularity","Popularity Calculated"], axis=1)
y = songCopy1["Popularity Calculated"]
print(X.shape, y.shape)

(154931, 14) (154931,)


In [31]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [36]:
songCopy_binary_encoded = pd.get_dummies(songCopy1, columns=["Artist", "TimeSignature","Explicit"])
songCopy_binary_encoded.head()

Unnamed: 0  Acousticness  Danceability  Duration  Energy  Instrumentalness  \
0           0      0.000728         0.520    234947   0.904          0.010300   
1           1      0.018200         0.581    239573   0.709          0.000664   
2           2      0.000473         0.572    198400   0.918          0.000431   
3           3      0.000970         0.596    231453   0.661          0.000033   
4           4      0.000036         0.520    222520   0.808          0.000010   

   Liveness  Loudness  Popularity Popularity Calculated  ...  Artist_t.A.T.u.  \
0    0.0634    -5.030          35      Mildly Unpopular  ...                0   
1    0.1740    -4.909          31      Mildly Unpopular  ...                0   
2    0.0977    -3.324          30      Mildly Unpopular  ...                0   
3    0.1130    -5.051          35      Mildly Unpopular  ...                0   
4    0.0800    -4.553          21            Unpopular   ...                0   

   Artist_twenty one pilots  Artist_will.i.am  TimeSignature_0  \
0                         0                 0                0   
1                         0                 0                0   
2                         0                 0                0   
3                         0                 0                0   
4                         0                 0                0   

   TimeSignature_1  TimeSignature_3  TimeSignature_4  TimeSignature_5  \
0                0                0                1                0   
1                0                0                1                0   
2                0                0                1                0   
3                0                0                1                0   
4                0                0                1                0   

   Explicit_False  Explicit_True  
0               1              0  
1               1              0  
2               1              0  
3               1              0  
4               1              0  

[5 rows x 1008 columns]

In [38]:
songCopy_binary_encoded.columns

Index(['Unnamed: 0', 'Acousticness', 'Danceability', 'Duration', 'Energy',
       'Instrumentalness', 'Liveness', 'Loudness', 'Popularity',
       'Popularity Calculated',
       ...
       'Artist_t.A.T.u.', 'Artist_twenty one pilots', 'Artist_will.i.am',
       'TimeSignature_0', 'TimeSignature_1', 'TimeSignature_3',
       'TimeSignature_4', 'TimeSignature_5', 'Explicit_False',
       'Explicit_True'],
      dtype='object', length=1008)

In [39]:
X = songCopy_binary_encoded.drop(["Popularity","Popularity Calculated","Unnamed: 0", "Artist_t.A.T.u.", "TimeSignature_1","Explicit_False"], axis=1)
y = songCopy_binary_encoded["Popularity Calculated"]
print(X.shape, y.shape)

(154931, 1002) (154931,)


In [40]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)

In [41]:
X_train.head()

Acousticness  Danceability  Duration  Energy  Instrumentalness  \
79441         0.0406         0.640    180333   0.771          0.000002   
40787         0.0609         0.712    235400   0.549          0.010300   
86983         0.0739         0.742    249253   0.627          0.000000   
124952        0.0201         0.471    185080   0.822          0.000000   
153569        0.6490         0.186    223933   0.428          0.000145   

        Liveness  Loudness  Speechiness    Tempo  Valence  ...  Artist_iio  \
79441     0.3260    -9.478       0.0306  138.745    0.860  ...           0   
40787     0.1090    -9.665       0.1880   95.758    0.345  ...           0   
86983     0.0796    -7.792       0.0457   92.994    0.597  ...           0   
124952    0.1050    -8.017       0.0538  140.007    0.363  ...           0   
153569    0.0877    -8.791       0.0320  163.975    0.273  ...           0   

        Artist_k.d. lang  Artist_matchbox twenty  Artist_twenty one pilots  \
79441                  0                       0                         0   
40787                  0                       0                         0   
86983                  0                       0                         0   
124952                 0                       0                         0   
153569                 0                       0                         0   

        Artist_will.i.am  TimeSignature_0  TimeSignature_3  TimeSignature_4  \
79441                  0                0                0                1   
40787                  0                0                0                1   
86983                  0                0                0                1   
124952                 0                0                0                1   
153569                 0                0                0                1   

        TimeSignature_5  Explicit_True  
79441                 0              0  
40787                 0              0  
86983                 0              0  
124952                0              0  
153569                0              0  

[5 rows x 1002 columns]

In [42]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [43]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [44]:
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [45]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [95]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=1002))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=4, activation='softmax'))

In [96]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [97]:
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_36 (Dense)             (None, 100)               100300    
_________________________________________________________________
dense_37 (Dense)             (None, 100)               10100     
_________________________________________________________________
dense_38 (Dense)             (None, 4)                 404       
Total params: 110,804
Trainable params: 110,804
Non-trainable params: 0
_________________________________________________________________


In [98]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=60,
    shuffle=True,
    verbose=2
)

Epoch 1/60
3632/3632 - 9s - loss: 0.6429 - accuracy: 0.7215
Epoch 2/60
3632/3632 - 9s - loss: 0.6006 - accuracy: 0.7390
Epoch 3/60
3632/3632 - 11s - loss: 0.5867 - accuracy: 0.7453
Epoch 4/60
3632/3632 - 10s - loss: 0.5762 - accuracy: 0.7497
Epoch 5/60
3632/3632 - 9s - loss: 0.5678 - accuracy: 0.7531
Epoch 6/60
3632/3632 - 9s - loss: 0.5605 - accuracy: 0.7563
Epoch 7/60
3632/3632 - 11s - loss: 0.5543 - accuracy: 0.7587
Epoch 8/60
3632/3632 - 10s - loss: 0.5481 - accuracy: 0.7615
Epoch 9/60
3632/3632 - 9s - loss: 0.5424 - accuracy: 0.7636
Epoch 10/60
3632/3632 - 10s - loss: 0.5370 - accuracy: 0.7657
Epoch 11/60
3632/3632 - 10s - loss: 0.5317 - accuracy: 0.7671
Epoch 12/60
3632/3632 - 9s - loss: 0.5261 - accuracy: 0.7700
Epoch 13/60
3632/3632 - 9s - loss: 0.5211 - accuracy: 0.7715
Epoch 14/60
3632/3632 - 11s - loss: 0.5161 - accuracy: 0.7734
Epoch 15/60
3632/3632 - 13s - loss: 0.5114 - accuracy: 0.7752
Epoch 16/60
3632/3632 - 9s - loss: 0.5062 - accuracy: 0.7777
Epoch 17/60
3632/3632 - 1

In [99]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

1211/1211 - 2s - loss: 0.9718 - accuracy: 0.7090
Normal Neural Network - Loss: 0.971758246421814, Accuracy: 0.708981990814209


In [104]:
encoded_predictions = model.predict_classes(X_test_scaled)
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [105]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test)}")

Predicted classes: ['Unpopular ' 'Unpopular ' 'Unpopular ' ... 'Unpopular '
 'Mildly Unpopular' 'Unpopular ']
Actual Labels: ['Unpopular ', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Mildly Unpopular', 'Mildly Unpopular', 'Mildly Unpopular', 'Unpopular ', 'Mildly Unpopular', 'Unpopular ', 'Unpopular ', 'Mildly Unpopular', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Mildly Unpopular', 'Unpopular ', 'Unpopular ', 'Mildly Unpopular', 'Mildly Unpopular', 'Mildly Unpopular', 'Unpopular ', 'Mildly Popular', 'Mildly Unpopular', 'Mildly Unpopular', 'Mildly Unpopular', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Mildly Unpopular', 'Unpopular ', 'Unpopular ', 'Mildly Popular', 'Mildly Unpopular', 'Mildly Unpopular', 'Unpopular ', 'Mildly Unpopular', 'Unpopular ', 'Mildly Popular', 'Unpopular ', 'Mildly Unpopular', 'Unpopular ', 'Unpopular ', 'Unpopular ', 'Mildly Unpopular'

In [103]:
print (prediction_labels )

['Unpopular ' 'Unpopular ' 'Unpopular ' 'Unpopular ' 'Unpopular ']


In [115]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 

In [116]:
results = confusion_matrix(y_test, prediction_labels) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(y_test, prediction_labels))
print ('Report : ')
print (classification_report(y_test, prediction_labels) )




Confusion Matrix :
[[  563  1118    25   604]
 [  564  5528     7  4660]
 [   39    26     5    16]
 [  239  3968     6 21365]]
Accuracy Score : 0.7089820050086489
Report : 
                  precision    recall  f1-score   support

  Mildly Popular       0.40      0.24      0.30      2310
Mildly Unpopular       0.52      0.51      0.52     10759
         Popular       0.12      0.06      0.08        86
      Unpopular        0.80      0.84      0.82     25578

        accuracy                           0.71     38733
       macro avg       0.46      0.41      0.43     38733
    weighted avg       0.70      0.71      0.70     38733

